feature: endpoint search
ISPP-Grupo5/BugaLink pull request #386
Opened 2023-04-07 18:26 UTC by Abrcobgal

2023-04-07 20:02 UTC, andrsdt requested changes
This is unusable in the front and does not comply with any REST standards, please make the requested changes

2023-04-08 14:26 UTC, andrsdt requested changes
* min_stars doesn't work, if I set min_stars=9999 I get results when there is no user with a score of 9999 (maximum is 5.0)

* date_from and date_to don't work, if I filter by dates between 2030-03-07 and 2030-03-08 I get back trips when in reality there are none

* hour_from and hour_to don't work, if I set the time between 00:00 and 00:01 I get back trips when in fact there are none

* min_price and max_price should be inclusive (max 4€ should include the 4€ ones). I have already fixed this.

2023-04-09 11:36 UTC, Abrcobgal commented on bugalink-backend/trips/views.py
> +            trips = Trip.objects.filter(status="PENDING")
Enrique will take this as his own issue, it will be like that for now as far as it works

2023-04-09 23:29 UTC, andrsdt approved these changes
I have made some big changes in the method that decreased the complexity significantly. Take note for the next time when you see a structure repeated many times (there were +10 if statements, all of them with the same structure). The code is much cleaner now.

![image](https://user-images.githubusercontent.com/53608787/230801429-7b049e05-0c28-4075-9bbe-b2acfc23e2a5.png)

I also fixed a bug that happened when there was only one trip left in the filter (it would never get removed) due to a misconception in python's mutable list capabilities. An example with many filters:

![image](https://user-images.githubusercontent.com/53608787/230801446-4726f398-210d-4d0a-b379-d50fd9b18eb3.png)

2023-04-09 23:31 UTC, merged