feat: add pending request count functionality
ISPP-Grupo5/BugaLink pull request #425
Opened 2023-04-13 16:45 UTC by andrsdt

2023-04-14 14:10 UTC, vicsotber requested changes
It appears to work fine, when there ir a trip request for the user the number appears
![image](https://user-images.githubusercontent.com/80173094/232067923-c988d80a-130f-434b-8bcb-dc60aaeddb00.png)

However when getting to the page it gives an error now.
![image](https://user-images.githubusercontent.com/80173094/232068292-add45cca-7042-4bd3-ad08-63419bb5d0d6.png)

This was revised locally.

2023-04-15 06:30 UTC, vicsotber commented
It looks like this problem is due to the profile picture. There is another task and another person taking care of it, so I guess you shouldn't have to worry about this error

2023-04-15 08:43 UTC, andrsdt commented
> It looks like this problem is due to the profile picture. There is another task and another person taking care of it, so I guess you shouldn't have to worry about this error

Great, we should not worry about it for now then. It looks like the fix can be adding the backend media folder to `next.config.js` as the error suggests :)

2023-04-15 12:44 UTC, vicsotber approved these changes

2023-04-15 12:44 UTC, merged