Pagar con Balance
ISPP-Grupo5/BugaLink pull request #429
Opened 2023-04-13 17:50 UTC by alvvazort

2023-04-13 18:50 UTC, pedparbas requested changes
Comentado todo lo referente al código, las transacciones parecen hacerse correctamente. 

Quedan algunos datos genéricos que deberían haber ya funciones que puedan sustituirlos.

Hay unos cambios que no deberían pertenecer a esta PR (Referido a TripRateViewSet). Borrar en caso de ser así.

Queda a la espera de la limpieza y conexión total con el frontend de momento.

2023-04-13 18:50 UTC, pedparbas commented on bugalink-backend/bugalink_backend/settings.py
Es necesario adjuntar por el canal de discord la modificación sobre el .env ya que desde el settings.py se intenta acceder al token de stripe y no existe. Falla.

2023-04-13 18:50 UTC, pedparbas commented on bugalink-backend/trips/tests.py
> +    '''
Este comentario es muy grande, ¿es útil para un desarrollo próximo o ya no sirve?

2023-04-13 18:50 UTC, pedparbas commented on bugalink-backend/trips/tests.py
> +    '''
Este comentario es muy grande, ¿es útil para un desarrollo próximo o ya no sirve?

2023-04-13 18:50 UTC, pedparbas commented on bugalink-backend/trips/views.py
> +                    currency="usd",
EUR no USD

2023-04-13 18:50 UTC, pedparbas commented on bugalink-backend/trips/views.py
> +class TripRateViewSet(
No debería ir en esta PR

2023-04-13 18:50 UTC, pedparbas commented on bugalink-frontend/pages/trips/[id]/pay.tsx
> +        note: "Example note"
Example note??

2023-04-13 18:50 UTC, pedparbas commented on bugalink-frontend/pages/trips/[id]/pay.tsx
>                data="**** **** **** 5678"
Datos genéricos que deberíamos poder ya hacer el retrieve de la base de datos.

2023-04-13 18:50 UTC, pedparbas commented on bugalink-frontend/pages/trips/[id]/pay.tsx
>                data="pedro@gmail.com"
Datos genéricos...

2023-04-13 21:42 UTC, andrsdt commented on bugalink-frontend/pages/trips/[id]/pay.tsx
>                data="**** **** **** 5678"
En cuanto al `**** **** **** 5678`, podemos traernos los 4 últimos dígitos de la CC de la base de datos y en el front lo pintamos con los asteriscos

2023-04-13 21:58 UTC, andrsdt requested changes
There are some important details to change before merging, apart from verifying that the functionality works, of course

2023-04-13 21:58 UTC, andrsdt commented on bugalink-backend/bugalink_backend/settings.py
> +CSRF_TRUSTED_ORIGINS = ["https://app.bugalink.es"]
También se usa `www.app.bugalink.es`

2023-04-13 21:58 UTC, andrsdt commented on bugalink-backend/trips/tests.py
> +class RequestTrip(TestCase):
These are tests "pa salir del paso" as they don't test any unitary functionality, if-else branches... such that the method could not work as expected and still return a code 201. In fact, there aren't any tests that make sure that invalid data results in errors and the objects not being created in the DB, which are probably the most important tests (everyone tests the happy path but there are always edge cases and misuse in the app)

2023-04-13 21:58 UTC, andrsdt commented on bugalink-backend/trips/views.py
> +                    "return_url": "http://app.bugalink.es",
What about development?? This has to use an environment variable defining that the front URL is either this or `localhost:3000`. Also, you are missing the "s" in "https://"

2023-04-13 21:58 UTC, andrsdt commented on bugalink-frontend/pages/trips/[id]/pay.tsx
> +              data={`${balance.amount}€`}
use `.toLocaleString()` as in other pages where we format numbers into money

2023-04-14 08:59 UTC, alvvazort commented on bugalink-backend/trips/views.py
> +class TripRateViewSet(
Deleted

2023-04-14 08:59 UTC, alvvazort commented on bugalink-frontend/pages/trips/[id]/pay.tsx
> +        note: "Example note"
Now is a real note from the user

2023-04-14 17:19 UTC, pedparbas approved these changes
Funciona 👍🏾

2023-04-14 17:19 UTC, pedparbas commented on bugalink-frontend/components/payment/CreditOperation.tsx
> +                return;
Dejar al menos un TO-DO para que quede reflejado y se vea más fácilmente

2023-04-14 17:19 UTC, pedparbas commented on bugalink-frontend/components/payment/CreditOperation.tsx
> +                return;
Lo mismo que en el comentario anterior

2023-04-14 17:44 UTC, merged