Feature/474 retirar saldo
ISPP-Grupo5/BugaLink pull request #509
Opened 2023-04-29 13:50 UTC by andrsdt

This PR contains:

* Withdraw balance functionality with all the corresponding validations. The IBAN validations is rather simple, it only verifies that it's 2 uppercase letters followed by 22 numbers
* Number
* Confirmation screens for successful withdrawing, unifying it with Marta's task on this topic
* Money input fields for easily implementing validations and restrictions. We were using the common text input field for money, which didn't format it correctly (without the € symbol, allowed more than 2 decimals, etc...)
* Transactions are now sorted by most recent date and not limited to 10. A transaction's receiver can now be `None` (representing that the user hasn't sent it to another user, but has withdrawed it to their bank account). **You have to run `migrate`** for this to apply.
* * Minor changes, bugfixes, typos corrections, etc.

2023-04-29 15:17 UTC, alvvazort requested changes
- [x] Withdraw.
- [x]  Validators.
- [x]  Money inputs.
- [x] Confirmation screen.
- [x]  Transaction (& sorted)

Simplemente una PR de Andrés, bastante placentero revisarle si me preguntan 👍.
Lo único es el comentario que he dejado de que se resta el dinero antes de comprobar si hay errores y que tal vez deba haber un mínimo de cantidad para retirar, pero casi que mejor no poner esto último porque así se ve mejor que funciona perfectamente poniendo lo que quieras.

2023-04-29 15:17 UTC, alvvazort commented on bugalink-backend/payment_methods/views.py
> +        balance.amount -= price
Se está cobrando antes de comprobar si hay errores. No entiendo la razón del cambio.

2023-04-29 15:17 UTC, alvvazort commented on bugalink-backend/payment_methods/views.py
> +        balance.amount -= price
Error mío, creo que siempre ha sido así el código. Pero sería mejor que estuviese dentro del bloque If.

2023-04-30 06:56 UTC, andrsdt commented
Ya he cambiado lo que me comentas de restar el saldo al crear el `TripRequest` dentro del if, cuando no hay errores. Además he añdido `@transaction.atomic` a los métodos de recargar saldo y pagar para asegurar que se haga un rollback si algo no sale bien, y evitar problemas como que reste el saldo pero no se cree el viaje. Tienes los cambios en [este commit](https://github.com/ISPP-Grupo5/BugaLink/pull/509/commits/8a9221772039fe0c34ad4c38340d064c5192ea8e).

2023-04-30 09:57 UTC, alvvazort approved these changes

2023-04-30 09:58 UTC, merged